export const collegeConstants = {
    COLLEGE_REQUEST: 'COLLEGE_CREATE_REQUEST',
    COLLEGE_SUCCESS: 'COLLEGE_CREATE_SUCCESS',
    COLLEGE_FAILURE: 'COLLEGE_CREATE_FAILURE',
  
  
    GETALL_COLLEGE_REQUEST: "COLLEGES_GETALL_REQUEST",
    GETALL_COLLEGE_SUCCESS: "COLLEGES_GETALL_SUCCESS",
    GETALL_COLLEGE_FAILURE: "COLLEGES_GETALL_FAILURE",
  
    DELETE_REQUEST: "COLLEGES_DELETE_REQUEST",
    DELETE_SUCCESS: "COLLEGES_DELETE_SUCCESS",
    DELETE_FAILURE: "COLLEGES_DELETE_FAILURE"
  };
  